SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE DATABASE IF NOT EXISTS `internetappli` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `internetappli`;

DROP TABLE IF EXISTS `players`;
CREATE TABLE `players` (
  `Name` varchar(50) NOT NULL,
  `Position` varchar(20) NOT NULL,
  `Team` varchar(30) NOT NULL,
  `Appearances` int(11) NOT NULL,
  `Goals` int(11) NOT NULL,
  `Assists` int(11) NOT NULL,
  `Cards` int(11) NOT NULL,
  `YellowCards` int(11) NOT NULL,
  `RedCards` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `players` (`Name`, `Position`, `Team`, `Appearances`, `Goals`, `Assists`, `Cards`, `YellowCards`, `RedCards`) VALUES
('Aaron Cresswell', 'Defender', 'West Ham United', 20, 0, 1, 1, 1, 0),
('Aaron Lennon', 'Midfielder', 'Burnley', 16, 1, 1, 1, 1, 0),
('Aaron Mooy', 'Midfielder', 'Huddersfield Town', 29, 3, 1, 4, 4, 0),
('Aaron Ramsey', 'Midfielder', 'Arsenal', 28, 4, 6, 0, 0, 0),
('Aaron Rowe', 'Forward', 'Huddersfield Town', 2, 0, 0, 0, 0, 0),
('Aaron Wan-Bissaka', 'Midfielder', 'Crystal Palace', 35, 0, 3, 6, 5, 1),
('Abdelhamid Sabiri', 'Midfielder', 'Huddersfield Town', 2, 0, 0, 0, 0, 0),
('Abdoulaye Doucoure', 'Midfielder', 'Watford', 35, 5, 6, 7, 7, 0),
('Aboubakar Kamara', 'Forward', 'Fulham', 13, 3, 0, 2, 2, 0),
('Adalberto Penaranda Maestre', 'Forward', 'Watford', 0, 0, 0, 0, 0, 0),
('Adam David Lallana', 'Midfielder', 'Liverpool', 13, 0, 0, 1, 1, 0),
('Adam Masina', 'Defender', 'Watford', 14, 0, 1, 5, 5, 0),
('Adam Smith', 'Defender', 'AFC Bournemouth', 25, 1, 1, 7, 6, 1),
('Adama Diakhaby', 'Forward', 'Huddersfield Town', 12, 0, 0, 1, 1, 0),
('Adama Traore Diarra', 'Midfielder', 'Wolverhampton Wanderers', 29, 1, 1, 1, 1, 0),
('Ademola Lookman', 'Forward', 'Everton', 21, 0, 2, 0, 0, 0),
('Adrian Mariappa', 'Defender', 'Watford', 26, 0, 0, 3, 3, 0),
('Adrian San Miguel del Castillo', 'Goalkeeper', 'West Ham United', 0, 0, 0, 0, 0, 0),
('Adrien Sebastian Perruchet Silva', 'Midfielder', 'Leicester City', 2, 0, 0, 0, 0, 0),
('Ainsley Maitland-Niles', 'Midfielder', 'Arsenal', 16, 1, 1, 4, 3, 1),
('Alberto Moreno', 'Defender', 'Liverpool', 2, 0, 0, 0, 0, 0),
('Aleksandar Mitrovic', 'Forward', 'Fulham', 37, 11, 3, 7, 7, 0),
('Alex Iwobi', 'Forward', 'Arsenal', 35, 3, 6, 0, 0, 0),
('Alex McCarthy', 'Goalkeeper', 'Southampton', 25, 0, 0, 1, 1, 0),
('Alex Oxlade-Chamberlain', 'Midfielder', 'Liverpool', 2, 0, 0, 0, 0, 0),
('Alex Pritchard', 'Midfielder', 'Huddersfield Town', 30, 2, 0, 2, 2, 0),
('Alex Smithies', 'Goalkeeper', 'Cardiff City', 0, 0, 0, 0, 0, 0),
('Alexander Sørloth', 'Forward', 'Crystal Palace', 12, 0, 0, 0, 0, 0),
('Alexandre Lacazette', 'Forward', 'Arsenal', 35, 13, 8, 2, 2, 0),
('Alexandre Nascimento Costa Silva', 'Forward', 'West Ham United', 1, 0, 0, 0, 0, 0),
('Alexis Sanchez', 'Forward', 'Manchester United', 20, 1, 3, 3, 3, 0),
('Alfie Jones', 'Defender', 'Southampton', 0, 0, 0, 0, 0, 0),
('Alfie Mawson', 'Defender', 'Fulham', 15, 0, 0, 2, 2, 0),
('Alfie Whiteman', 'Goalkeeper', 'Tottenham Hotspur', 0, 0, 0, 0, 0, 0),
('Ali Koiki', 'Defender', 'Burnley', 0, 0, 0, 0, 0, 0),
('Alireza Jahanbakhsh', 'Forward', 'Brighton & Hove Albion', 19, 0, 0, 2, 2, 0),
('Alisson Becker', 'Goalkeeper', 'Liverpool', 38, 0, 0, 1, 1, 0),
('Alvaro Morata', 'Forward', 'Chelsea', 16, 5, 0, 3, 3, 0),
('Ander Herrera', 'Midfielder', 'Manchester United', 22, 2, 3, 4, 4, 0),
('Andre Filipe Tavares Gomes', 'Midfielder', 'Everton', 27, 1, 1, 7, 7, 0),
('Andre Gray', 'Forward', 'Watford', 29, 7, 2, 2, 2, 0),
('Andre Schürrle', 'Midfielder', 'Fulham', 24, 6, 0, 2, 2, 0),
('Andre-Frank Zambo Anguissa', 'Midfielder', 'Fulham', 22, 0, 0, 4, 3, 1),
('Andreas Christensen', 'Defender', 'Chelsea', 8, 0, 0, 1, 1, 0),
('Andreas Pereira', 'Midfielder', 'Manchester United', 15, 1, 1, 5, 5, 0),
('Andrew Robertson', 'Defender', 'Liverpool', 36, 0, 11, 4, 4, 0),
('Andrew Surman', 'Midfielder', 'AFC Bournemouth', 18, 0, 0, 2, 2, 0),
('Andriy Yarmolenko', 'Forward', 'West Ham United', 9, 2, 0, 2, 2, 0),
('Andros Townsend', 'Midfielder', 'Crystal Palace', 38, 6, 4, 1, 1, 0),
('Andy Carroll', 'Forward', 'West Ham United', 12, 0, 0, 2, 2, 0),
('Angel Gomes', 'Midfielder', 'Manchester United', 2, 0, 0, 0, 0, 0),
('Angelo Ogbonna', 'Defender', 'West Ham United', 24, 1, 1, 2, 2, 0),
('Angus Gunn', 'Goalkeeper', 'Southampton', 12, 0, 0, 0, 0, 0),
('Anthony Driscoll-Glennon', 'Defender', 'Burnley', 0, 0, 0, 0, 0, 0),
('Anthony Knockaert', 'Midfielder', 'Brighton & Hove Albion', 30, 2, 6, 6, 5, 1),
('Anthony Martial', 'Forward', 'Manchester United', 27, 10, 2, 2, 2, 0),
('Antonio Barreca', 'Defender', 'Newcastle United', 1, 0, 0, 0, 0, 0),
('Antonio Rüdiger', 'Defender', 'Chelsea', 33, 1, 0, 7, 7, 0),
('Antonio Valencia', 'Defender', 'Manchester United', 6, 0, 0, 2, 2, 0),
('Arijanet Muric', 'Goalkeeper', 'Manchester City', 0, 0, 0, 0, 0, 0),
('Aron Einar Gunnarsson', 'Midfielder', 'Cardiff City', 28, 1, 1, 5, 5, 0),
('Arthur Masuaku', 'Defender', 'West Ham United', 23, 0, 1, 2, 2, 0),
('Artur Boruc', 'Goalkeeper', 'AFC Bournemouth', 12, 0, 0, 2, 2, 0),
('Ashley Barnes', 'Forward', 'Burnley', 37, 12, 2, 8, 8, 0),
('Ashley Westwood', 'Midfielder', 'Burnley', 34, 2, 7, 5, 5, 0),
('Ashley Young', 'Midfielder', 'Manchester United', 30, 2, 2, 11, 10, 1),
('Asmir Begovic', 'Goalkeeper', 'AFC Bournemouth', 24, 0, 0, 0, 0, 0),
('Aymeric Laporte', 'Defender', 'Manchester City', 35, 3, 3, 3, 3, 0),
('Ayoze Perez', 'Forward', 'Newcastle United', 37, 12, 2, 2, 2, 0),
('Bakary Sako', 'Midfielder', 'Crystal Palace', 4, 0, 0, 0, 0, 0),
('Bakayo Sako', 'Midfielder', 'Arsenal', 1, 0, 0, 0, 0, 0),
('Ben Chilwell', 'Defender', 'Leicester City', 36, 0, 4, 4, 4, 0),
('Ben Davies', 'Defender', 'Tottenham Hotspur', 27, 0, 0, 2, 2, 0),
('Ben Foster', 'Goalkeeper', 'Watford', 38, 0, 0, 1, 1, 0),
('Ben Gibson', 'Defender', 'Burnley', 1, 1, 0, 1, 1, 0),
('Ben Hamer', 'Goalkeeper', 'Huddersfield Town', 7, 0, 0, 0, 0, 0),
('Ben Mee', 'Defender', 'Burnley', 38, 0, 2, 9, 9, 0),
('Ben White', 'Defender', 'Brighton & Hove Albion', 0, 0, 0, 0, 0, 0),
('Ben Wilmot', 'Defender', 'Watford', 2, 0, 0, 0, 0, 0),
('Benjamin Johnson', 'Forward', 'West Ham United', 1, 0, 0, 0, 0, 0),
('Benjamin Mendy', 'Defender', 'Manchester City', 10, 0, 5, 1, 1, 0),
('Beram Kayal', 'Midfielder', 'Brighton & Hove Albion', 18, 1, 1, 4, 4, 0),
('Bernard Anicio Caldeira Duarte', 'Midfielder', 'Everton', 34, 1, 3, 5, 5, 0),
('Bernardo', 'Defender', 'Brighton & Hove Albion', 22, 0, 1, 4, 4, 0),
('Bernardo Silva', 'Midfielder', 'Manchester City', 36, 7, 7, 3, 3, 0),
('Bernd Leno', 'Goalkeeper', 'Arsenal', 32, 0, 0, 0, 0, 0),
('Bobby Reid', 'Midfielder', 'Cardiff City', 27, 5, 2, 0, 0, 0),
('Brian Murphy', 'Goalkeeper', 'Cardiff City', 0, 0, 0, 0, 0, 0),
('Bright Enobakhare', 'Forward', 'Wolverhampton Wanderers', 0, 0, 0, 0, 0, 0),
('Bruno Ecuele Manga', 'Defender', 'Cardiff City', 38, 0, 1, 0, 0, 0),
('Bruno Saltor Grau', 'Defender', 'Brighton & Hove Albion', 14, 0, 1, 2, 2, 0),
('Caglar Soyuncu', 'Defender', 'Leicester City', 6, 0, 0, 1, 1, 0),
('Callum Hudson-Odoi', 'Midfielder', 'Chelsea', 10, 0, 1, 0, 0, 0),
('Callum Paterson', 'Defender', 'Cardiff City', 27, 4, 1, 4, 4, 0),
('Callum Roberts', 'Forward', 'Newcastle United', 0, 0, 0, 0, 0, 0),
('Callum Slattery', 'Midfielder', 'Southampton', 3, 0, 0, 0, 0, 0),
('Callum Wilson', 'Forward', 'AFC Bournemouth', 30, 14, 9, 3, 3, 0),
('Calum Chambers', 'Defender', 'Fulham', 31, 2, 0, 9, 9, 0),
('Cameron John', 'Defender', 'Wolverhampton Wanderers', 0, 0, 0, 0, 0, 0),
('Carl Jenkinson', 'Defender', 'Arsenal', 3, 0, 0, 0, 0, 0),
('Carlos Sanchez', 'Midfielder', 'West Ham United', 7, 0, 0, 0, 0, 0),
('Cedric Soares', 'Defender', 'Southampton', 18, 1, 2, 4, 4, 0),
('Cenk Tosun', 'Forward', 'Everton', 25, 3, 3, 3, 3, 0),
('Cesar Azpilicueta', 'Defender', 'Chelsea', 38, 1, 5, 4, 4, 0),
('Cesc Fabregas', 'Midfielder', 'Chelsea', 6, 0, 0, 1, 1, 0),
('Charlie Austin', 'Forward', 'Southampton', 25, 2, 2, 1, 1, 0),
('Charlie Daniels', 'Defender', 'AFC Bournemouth', 21, 1, 0, 4, 4, 0),
('Charlie Taylor', 'Defender', 'Burnley', 38, 0, 1, 2, 2, 0),
('Cheikhou Kouyate', 'Midfielder', 'Crystal Palace', 31, 0, 2, 3, 3, 0),
('Chris Löwe', 'Defender', 'Huddersfield Town', 29, 0, 2, 2, 2, 0),
('Chris Mepham', 'Defender', 'AFC Bournemouth', 13, 0, 1, 1, 1, 0),
('Chris Smalling', 'Defender', 'Manchester United', 24, 1, 0, 1, 1, 0),
('Chris Wood', 'Forward', 'Burnley', 38, 10, 2, 2, 2, 0),
('Christian Atsu Twasam', 'Midfielder', 'Newcastle United', 28, 1, 0, 2, 2, 0),
('Christian Benteke', 'Forward', 'Crystal Palace', 16, 1, 1, 1, 1, 0),
('Christian Eriksen', 'Midfielder', 'Tottenham Hotspur', 35, 8, 12, 3, 3, 0),
('Christian Fuchs', 'Defender', 'Leicester City', 3, 0, 0, 0, 0, 0),
('Christian Kabasele', 'Defender', 'Watford', 21, 0, 0, 5, 4, 1),
('Christopher Schindler', 'Defender', 'Huddersfield Town', 37, 1, 0, 7, 6, 1),
('Ciaran Clark', 'Defender', 'Newcastle United', 11, 3, 0, 1, 1, 0),
('Claudio Andres Bravo Muñoz', 'Goalkeeper', 'Manchester City', 0, 0, 0, 0, 0, 0),
('Collin Quaner', 'Forward', 'Huddersfield Town', 2, 0, 0, 0, 0, 0),
('Connor Wickham', 'Forward', 'Crystal Palace', 6, 0, 1, 0, 0, 0),
('Conor Coady', 'Midfielder', 'Wolverhampton Wanderers', 38, 0, 0, 5, 5, 0),
('Conor Coventry', 'Midfielder', 'West Ham United', 0, 0, 0, 0, 0, 0),
('Craig Cathcart', 'Defender', 'Watford', 36, 3, 0, 2, 2, 0),
('Curtis Jones', 'Midfielder', 'Liverpool', 0, 0, 0, 0, 0, 0),
('Cyrus Christie', 'Defender', 'Fulham', 28, 0, 1, 7, 7, 0),
('Dale Stephens', 'Midfielder', 'Brighton & Hove Albion', 30, 1, 1, 8, 7, 1),
('Damian Emiliano Martinez', 'Goalkeeper', 'Arsenal', 0, 0, 0, 0, 0, 0),
('Dan Burn', 'Defender', 'Brighton & Hove Albion', 0, 0, 0, 0, 0, 0),
('Dan Gosling', 'Midfielder', 'AFC Bournemouth', 25, 2, 1, 8, 8, 0),
('Daniel Amartey', 'Midfielder', 'Leicester City', 9, 0, 0, 2, 2, 0),
('Daniel Sturridge', 'Forward', 'Liverpool', 18, 2, 1, 1, 1, 0),
('Daniel William John Ings', 'Forward', 'Southampton', 24, 7, 3, 1, 1, 0),
('Daniel Williams', 'Midfielder', 'Huddersfield Town', 5, 0, 0, 1, 1, 0),
('Danilo', 'Defender', 'Manchester City', 11, 1, 0, 1, 1, 0),
('Danny Drinkwater', 'Midfielder', 'Chelsea', 0, 0, 0, 0, 0, 0),
('Danny Rose', 'Defender', 'Tottenham Hotspur', 26, 0, 3, 5, 5, 0),
('Danny Simpson', 'Defender', 'Leicester City', 6, 0, 0, 0, 0, 0),
('Danny Ward', 'Goalkeeper', 'Leicester City', 0, 0, 0, 0, 0, 0),
('Danny Welbeck', 'Forward', 'Arsenal', 8, 1, 1, 0, 0, 0),
('Daryl Janmaat', 'Defender', 'Watford', 18, 0, 2, 3, 3, 0),
('David Brooks', 'Forward', 'AFC Bournemouth', 30, 7, 5, 3, 3, 0),
('David Button', 'Goalkeeper', 'Brighton & Hove Albion', 4, 0, 0, 0, 0, 0),
('David de Gea', 'Goalkeeper', 'Manchester United', 38, 0, 0, 1, 1, 0),
('David Junior Hoilett', 'Forward', 'Cardiff City', 32, 3, 1, 4, 4, 0),
('David Luiz', 'Defender', 'Chelsea', 36, 3, 2, 3, 3, 0),
('David Silva', 'Midfielder', 'Manchester City', 33, 6, 8, 3, 3, 0),
('Davide Zappacosta', 'Defender', 'Chelsea', 4, 0, 0, 0, 0, 0),
('Davinson Sanchez Mina', 'Defender', 'Tottenham Hotspur', 23, 1, 1, 2, 2, 0),
('Davy Pröpper', 'Midfielder', 'Brighton & Hove Albion', 30, 1, 1, 2, 2, 0),
('DeAndre Yedlin', 'Defender', 'Newcastle United', 29, 1, 2, 8, 7, 1),
('Declan Rice', 'Midfielder', 'West Ham United', 34, 2, 0, 4, 4, 0),
('Dejan Lovren', 'Defender', 'Liverpool', 13, 1, 0, 1, 1, 0),
('Dele Alli', 'Midfielder', 'Tottenham Hotspur', 25, 5, 3, 4, 4, 0),
('Demarai Gray', 'Midfielder', 'Leicester City', 34, 4, 1, 2, 2, 0),
('Demeaco Duhaney', 'Defender', 'Huddersfield Town', 1, 0, 0, 0, 0, 0),
('Denis Odoi', 'Defender', 'Fulham', 31, 0, 1, 4, 4, 0),
('Denis Suarez', 'Midfielder', 'Arsenal', 4, 0, 0, 0, 0, 0),
('Diego Rico', 'Defender', 'AFC Bournemouth', 12, 0, 0, 1, 1, 0),
('Diogo Jose Teixeira da Silva', 'Midfielder', 'Wolverhampton Wanderers', 33, 9, 5, 11, 11, 0),
('Divock Origi', 'Forward', 'Liverpool', 12, 3, 1, 0, 0, 0),
('Domingos Quina', 'Midfielder', 'Watford', 8, 1, 0, 0, 0, 0),
('Dominic Calvert-Lewin', 'Forward', 'Everton', 35, 6, 2, 3, 3, 0),
('Dominic Solanke', 'Forward', 'AFC Bournemouth', 10, 0, 1, 0, 0, 0),
('Dwight McNeil', 'Forward', 'Burnley', 21, 3, 5, 2, 2, 0),
('Eden Hazard', 'Midfielder', 'Chelsea', 37, 16, 15, 2, 2, 0),
('Ederson', 'Goalkeeper', 'Manchester City', 38, 0, 1, 2, 2, 0),
('Edward Nketiah', 'Forward', 'Arsenal', 5, 1, 0, 0, 0, 0),
('Elias Kachunga', 'Forward', 'Huddersfield Town', 20, 0, 0, 2, 2, 0),
('Emerson Hyndman', 'Midfielder', 'AFC Bournemouth', 1, 0, 0, 0, 0, 0),
('Emerson Palmieri dos Santos', 'Defender', 'Chelsea', 10, 0, 0, 0, 0, 0),
('Emile Smith Rowe', 'Midfielder', 'Arsenal', 0, 0, 0, 0, 0, 0),
('Eric Bertrand Bailly', 'Defender', 'Manchester United', 12, 0, 0, 2, 1, 1),
('Eric Dier', 'Midfielder', 'Tottenham Hotspur', 20, 3, 0, 4, 4, 0),
('Erik Durm', 'Defender', 'Huddersfield Town', 28, 0, 1, 0, 0, 0),
('Erik Lamela', 'Midfielder', 'Tottenham Hotspur', 19, 4, 2, 2, 2, 0),
('Ethan Ampadu', 'Midfielder', 'Chelsea', 0, 0, 0, 0, 0, 0),
('Etienne Capoue', 'Midfielder', 'Watford', 33, 1, 3, 16, 15, 1),
('Fabian Cornelio Balbuena Gonzalez', 'Defender', 'West Ham United', 23, 1, 0, 2, 2, 0),
('Fabian Delph', 'Midfielder', 'Manchester City', 11, 0, 1, 3, 2, 1),
('Fabian Schär', 'Defender', 'Newcastle United', 24, 4, 1, 12, 12, 0),
('Fabinho', 'Midfielder', 'Liverpool', 28, 1, 2, 6, 6, 0),
('Fabricio Martin Agosto Ramirez', 'Goalkeeper', 'Fulham', 2, 0, 0, 0, 0, 0),
('Faustino Marcos Alberto Rojo', 'Defender', 'Manchester United', 5, 0, 0, 2, 2, 0),
('Federico Fernandez', 'Defender', 'Newcastle United', 19, 0, 1, 2, 2, 0),
('Felipe Anderson Pereira Gomes', 'Midfielder', 'West Ham United', 36, 9, 4, 3, 3, 0),
('Fernando Llorente Torres', 'Forward', 'Tottenham Hotspur', 20, 1, 4, 2, 2, 0),
('Fernando Luiz Rosa', 'Midfielder', 'Manchester City', 29, 1, 3, 5, 5, 0),
('Florent Hadergjonaj', 'Defender', 'Huddersfield Town', 24, 0, 0, 1, 1, 0),
('Florian Lejeune', 'Defender', 'Newcastle United', 12, 0, 0, 0, 0, 0),
('Florin Andone', 'Forward', 'Brighton & Hove Albion', 23, 3, 0, 5, 5, 0),
('Floyd Ayite', 'Midfielder', 'Fulham', 16, 1, 0, 0, 0, 0),
('Fousseni Diabate', 'Midfielder', 'Leicester City', 1, 0, 0, 0, 0, 0),
('Francisco Femenia Far', 'Midfielder', 'Watford', 29, 1, 1, 1, 1, 0),
('Fraser Forster', 'Goalkeeper', 'Southampton', 1, 0, 0, 0, 0, 0),
('Freddie Woodman', 'Goalkeeper', 'Newcastle United', 0, 0, 0, 0, 0, 0),
('Frederico Rodrigues Santos', 'Midfielder', 'Manchester United', 17, 1, 1, 2, 2, 0),
('Gabriel Jesus', 'Forward', 'Manchester City', 29, 7, 3, 1, 1, 0),
('Gaetan Bong Songo', 'Defender', 'Brighton & Hove Albion', 22, 0, 0, 0, 0, 0),
('Gary Cahill', 'Defender', 'Chelsea', 2, 0, 0, 0, 0, 0),
('Gary Madine', 'Forward', 'Cardiff City', 5, 0, 0, 0, 0, 0),
('George Marsh', 'Midfielder', 'Tottenham Hotspur', 0, 0, 0, 0, 0, 0),
('Georges-Kevin N\'Koudou Mbida', 'Forward', 'Tottenham Hotspur', 1, 0, 1, 0, 0, 0),
('Georginio Wijnaldum', 'Midfielder', 'Liverpool', 35, 3, 0, 3, 3, 0),
('Gerard Deulofeu', 'Forward', 'Watford', 30, 10, 5, 3, 3, 0),
('Glenn Murray', 'Forward', 'Brighton & Hove Albion', 38, 13, 1, 5, 5, 0),
('Gonzalo Higuain', 'Forward', 'Chelsea', 14, 5, 0, 0, 0, 0),
('Grady Diangana', 'Midfielder', 'West Ham United', 17, 0, 1, 0, 0, 0),
('Granit Xhaka', 'Midfielder', 'Arsenal', 29, 4, 2, 10, 10, 0),
('Greg Cunningham', 'Defender', 'Cardiff City', 7, 0, 0, 3, 3, 0),
('Gylfi Sigurdsson', 'Midfielder', 'Everton', 38, 13, 6, 3, 3, 0),
('Hamza Choudhury', 'Midfielder', 'Leicester City', 9, 0, 0, 0, 0, 0),
('Harry Arter', 'Midfielder', 'Cardiff City', 25, 0, 1, 10, 10, 0),
('Harry Kane', 'Forward', 'Tottenham Hotspur', 28, 17, 4, 5, 5, 0),
('Harry Maguire', 'Defender', 'Leicester City', 31, 3, 0, 8, 7, 1),
('Harry Winks', 'Midfielder', 'Tottenham Hotspur', 26, 1, 0, 4, 4, 0),
('Harvey Elliot', 'Forward', 'Fulham', 2, 0, 0, 0, 0, 0),
('Harvey Lewis Barnes', 'Midfielder', 'Leicester City', 16, 1, 2, 0, 0, 0),
('Håvard Nordtveit', 'Midfielder', 'Fulham', 5, 0, 1, 0, 0, 0),
('Hector Bellerin', 'Defender', 'Arsenal', 19, 0, 5, 3, 3, 0),
('Helder Wander Sousa Azevedo Costa', 'Midfielder', 'Wolverhampton Wanderers', 25, 1, 2, 3, 3, 0),
('Henrikh Mkhitaryan', 'Midfielder', 'Arsenal', 25, 6, 4, 1, 1, 0),
('Heung-Min Son', 'Forward', 'Tottenham Hotspur', 31, 12, 6, 4, 3, 1),
('Heurelho da Silva Gomes', 'Goalkeeper', 'Watford', 0, 0, 0, 0, 0, 0),
('Hugo Lloris', 'Goalkeeper', 'Tottenham Hotspur', 33, 0, 0, 0, 0, 0),
('Ibrahima Cisse', 'Midfielder', 'Fulham', 3, 0, 0, 0, 0, 0),
('Idrissa Gana Gueye', 'Midfielder', 'Everton', 33, 0, 2, 6, 6, 0),
('Ilkay Gündogan', 'Midfielder', 'Manchester City', 31, 6, 3, 3, 3, 0),
('Isaac Ajayi Success', 'Forward', 'Watford', 30, 1, 1, 4, 4, 0),
('Isaac Hayden', 'Midfielder', 'Newcastle United', 25, 1, 4, 5, 4, 1),
('Isaac Mbenza', 'Forward', 'Huddersfield Town', 22, 1, 1, 1, 1, 0),
('Issa Diop', 'Defender', 'West Ham United', 33, 1, 0, 4, 4, 0),
('Ivan Ricardo Neves Abreu Cavaleiro', 'Forward', 'Wolverhampton Wanderers', 23, 3, 1, 1, 1, 0),
('Jack Cork', 'Midfielder', 'Burnley', 37, 1, 2, 6, 6, 0),
('Jack Simpson', 'Defender', 'AFC Bournemouth', 6, 0, 0, 0, 0, 0),
('Jack Stephens', 'Defender', 'Southampton', 24, 1, 0, 4, 4, 0),
('Jack Wilshere', 'Midfielder', 'West Ham United', 8, 0, 1, 2, 2, 0),
('Jacob Murphy', 'Midfielder', 'Newcastle United', 9, 0, 1, 0, 0, 0),
('Jairo Riedewald', 'Defender', 'Crystal Palace', 0, 0, 0, 0, 0, 0),
('Jamal Lascelles', 'Defender', 'Newcastle United', 32, 0, 1, 4, 4, 0),
('James Garner', 'Defender', 'Manchester United', 1, 0, 0, 0, 0, 0),
('James Maddison', 'Midfielder', 'Leicester City', 36, 7, 7, 6, 5, 1),
('James McArthur', 'Midfielder', 'Crystal Palace', 38, 3, 6, 7, 7, 0),
('James McCarthy', 'Midfielder', 'Everton', 1, 0, 0, 0, 0, 0),
('James Milner', 'Midfielder', 'Liverpool', 31, 5, 4, 8, 7, 1),
('James Tarkowski', 'Defender', 'Burnley', 35, 3, 1, 8, 8, 0),
('James Tomkins', 'Defender', 'Crystal Palace', 29, 1, 1, 6, 6, 0),
('James Ward-Prowse', 'Midfielder', 'Southampton', 26, 7, 0, 4, 4, 0),
('Jamie Sterry', 'Defender', 'Newcastle United', 0, 0, 0, 0, 0, 0),
('Jamie Vardy', 'Forward', 'Leicester City', 34, 18, 4, 5, 4, 1),
('Jan Bednarek', 'Defender', 'Southampton', 25, 0, 1, 7, 7, 0),
('Jan Vertonghen', 'Defender', 'Tottenham Hotspur', 22, 1, 0, 6, 5, 1),
('Jannik Vestergaard', 'Defender', 'Southampton', 23, 0, 0, 2, 2, 0),
('Jason Puncheon', 'Midfielder', 'Huddersfield Town', 11, 0, 0, 1, 1, 0),
('Jason Steele', 'Goalkeeper', 'Brighton & Hove Albion', 0, 0, 0, 0, 0, 0),
('Javier Hernandez', 'Forward', 'West Ham United', 25, 7, 1, 2, 2, 0),
('Javier Manquillo Gaitan', 'Defender', 'Newcastle United', 18, 0, 3, 2, 2, 0),
('Jayson Molumby', 'Midfielder', 'Brighton & Hove Albion', 0, 0, 0, 0, 0, 0),
('Jazz Richards', 'Defender', 'Cardiff City', 4, 0, 0, 0, 0, 0),
('Jean Michael Seri', 'Midfielder', 'Fulham', 32, 1, 2, 6, 6, 0),
('Jeff Hendrick', 'Midfielder', 'Burnley', 32, 3, 0, 4, 4, 0),
('Jefferson Lerma', 'Midfielder', 'AFC Bournemouth', 30, 2, 0, 12, 12, 0),
('Jeffrey Schlupp', 'Defender', 'Crystal Palace', 30, 4, 1, 1, 1, 0),
('Jermain Defoe', 'Forward', 'AFC Bournemouth', 4, 0, 0, 0, 0, 0),
('Jesse Lingard', 'Midfielder', 'Manchester United', 27, 4, 2, 3, 3, 0),
('Joao Moutinho', 'Midfielder', 'Wolverhampton Wanderers', 38, 1, 8, 4, 4, 0),
('Joe Bennett', 'Defender', 'Cardiff City', 30, 0, 1, 5, 5, 0),
('Joe Bryan', 'Defender', 'Fulham', 28, 0, 1, 5, 5, 0),
('Joe Daniel Tupper', 'Goalkeeper', 'Crystal Palace', 0, 0, 0, 0, 0, 0),
('Joe Gomez', 'Defender', 'Liverpool', 16, 0, 0, 2, 2, 0),
('Joe Hart', 'Goalkeeper', 'Burnley', 19, 0, 0, 0, 0, 0),
('Joe Powell', 'Forward', 'West Ham United', 0, 0, 0, 0, 0, 0),
('Joe Ralls', 'Midfielder', 'Cardiff City', 28, 0, 0, 6, 5, 1),
('Joel Coleman', 'Goalkeeper', 'Huddersfield Town', 1, 0, 0, 0, 0, 0),
('Joel Matip', 'Defender', 'Liverpool', 22, 1, 0, 3, 3, 0),
('Joel Ward', 'Defender', 'Crystal Palace', 7, 1, 0, 1, 1, 0),
('Johann Berg Gudmundsson', 'Midfielder', 'Burnley', 29, 3, 6, 2, 2, 0),
('John Ruddy', 'Goalkeeper', 'Wolverhampton Wanderers', 1, 0, 0, 0, 0, 0),
('John Stones', 'Defender', 'Manchester City', 24, 0, 0, 1, 1, 0),
('Jon Gorenc Stankovic', 'Defender', 'Huddersfield Town', 11, 1, 0, 2, 2, 0),
('Jonas Lossl', 'Goalkeeper', 'Huddersfield Town', 31, 0, 1, 1, 1, 0),
('Jonathan Hogg', 'Midfielder', 'Huddersfield Town', 29, 0, 1, 10, 9, 1),
('Jonathan Walters', 'Forward', 'Burnley', 0, 0, 0, 0, 0, 0),
('Jonjo Shelvey', 'Midfielder', 'Newcastle United', 16, 1, 1, 1, 1, 0),
('Jonjoe Kenny', 'Defender', 'Everton', 10, 0, 1, 1, 1, 0),
('Jonny', 'Defender', 'Wolverhampton Wanderers', 33, 1, 1, 6, 6, 0),
('Jonny Evans', 'Defender', 'Leicester City', 24, 1, 0, 2, 2, 0),
('Jordan Ayew', 'Forward', 'Crystal Palace', 20, 1, 2, 3, 3, 0),
('Jordan Henderson', 'Midfielder', 'Liverpool', 32, 1, 3, 4, 3, 1),
('Jordan Pickford', 'Goalkeeper', 'Everton', 38, 0, 0, 1, 1, 0),
('Jordon Ibe', 'Midfielder', 'AFC Bournemouth', 19, 1, 1, 1, 1, 0),
('Jorginho', 'Midfielder', 'Chelsea', 37, 2, 0, 8, 8, 0),
('Jose Diogo Dalot Teixeira', 'Defender', 'Manchester United', 16, 0, 2, 3, 3, 0),
('Jose Holebas', 'Defender', 'Watford', 28, 3, 6, 14, 13, 1),
('Jose Izquierdo', 'Forward', 'Brighton & Hove Albion', 15, 0, 1, 1, 1, 0),
('Jose Luis Sanmartin Mato', 'Forward', 'Newcastle United', 16, 2, 0, 1, 1, 0),
('Joseph Willock', 'Midfielder', 'Arsenal', 2, 0, 0, 0, 0, 0),
('Josh Benson', 'Midfielder', 'Burnley', 0, 0, 0, 0, 0, 0),
('Josh Knight', 'Defender', 'Leicester City', 0, 0, 0, 0, 0, 0),
('Josh Murphy', 'Forward', 'Cardiff City', 29, 3, 2, 2, 2, 0),
('Joshua King', 'Forward', 'AFC Bournemouth', 35, 12, 3, 3, 3, 0),
('Joshua Sims', 'Midfielder', 'Southampton', 7, 0, 1, 0, 0, 0),
('Juan Marcos Foyth', 'Defender', 'Tottenham Hotspur', 12, 1, 0, 5, 4, 1),
('Juan Mata', 'Midfielder', 'Manchester United', 22, 3, 2, 3, 3, 0),
('Julian Speroni', 'Goalkeeper', 'Crystal Palace', 1, 0, 0, 0, 0, 0),
('Juninho Bacuna', 'Midfielder', 'Huddersfield Town', 21, 1, 0, 4, 4, 0),
('Junior Stanislas', 'Midfielder', 'AFC Bournemouth', 23, 2, 3, 1, 1, 0),
('Jürgen Locadia', 'Forward', 'Brighton & Hove Albion', 26, 2, 0, 1, 1, 0),
('Kadeem Harris', 'Midfielder', 'Cardiff City', 13, 1, 0, 1, 1, 0),
('Karl Darlow', 'Goalkeeper', 'Newcastle United', 0, 0, 0, 0, 0, 0),
('Karlan Ahearne-Grant', 'Forward', 'Huddersfield Town', 13, 4, 0, 0, 0, 0),
('Kasper Schmeichel', 'Goalkeeper', 'Leicester City', 38, 0, 0, 3, 3, 0),
('Kayne Ramsey', 'Midfielder', 'Southampton', 1, 0, 0, 0, 0, 0),
('Kazaiah Sterling', 'Forward', 'Tottenham Hotspur', 0, 0, 0, 0, 0, 0),
('Kelechi Iheanacho', 'Forward', 'Leicester City', 30, 1, 3, 2, 2, 0),
('Kelland Watts', 'Midfielder', 'Newcastle United', 0, 0, 0, 0, 0, 0),
('Ken Sema', 'Midfielder', 'Watford', 17, 1, 2, 1, 1, 0),
('Kenneth Dahrup Zohorè', 'Forward', 'Cardiff City', 19, 1, 1, 1, 1, 0),
('Kepa Arrizabalaga', 'Goalkeeper', 'Chelsea', 36, 0, 0, 2, 2, 0),
('Kevin De Bruyne', 'Midfielder', 'Manchester City', 19, 2, 2, 2, 2, 0),
('Kevin Long', 'Defender', 'Burnley', 6, 0, 1, 0, 0, 0),
('Kevin McDonald', 'Midfielder', 'Fulham', 15, 0, 0, 7, 6, 1),
('Kieran Dowell', 'Midfielder', 'Everton', 0, 0, 0, 0, 0, 0),
('Kieran Trippier', 'Defender', 'Tottenham Hotspur', 27, 1, 3, 2, 2, 0),
('Konstantinos Mavropanos', 'Defender', 'Arsenal', 4, 0, 0, 1, 1, 0),
('Kortney Hause', 'Defender', 'Wolverhampton Wanderers', 0, 0, 0, 0, 0, 0),
('Kurt Zouma', 'Defender', 'Everton', 32, 2, 2, 6, 5, 1),
('Kyle Taylor', 'Midfielder', 'AFC Bournemouth', 0, 0, 0, 0, 0, 0),
('Kyle Walker', 'Defender', 'Manchester City', 33, 1, 1, 3, 3, 0),
('Kyle Walker-Peters', 'Defender', 'Tottenham Hotspur', 6, 0, 3, 1, 1, 0),
('Laurent Depoitre', 'Forward', 'Huddersfield Town', 23, 0, 1, 1, 1, 0),
('Laurent Koscielny', 'Defender', 'Arsenal', 17, 3, 0, 1, 1, 0),
('Lazar Markovic', 'Midfielder', 'Fulham', 1, 0, 0, 0, 0, 0),
('Leander Dendoncker', 'Midfielder', 'Wolverhampton Wanderers', 19, 2, 0, 1, 1, 0),
('Leandro Bacuna', 'Midfielder', 'Cardiff City', 11, 0, 0, 2, 2, 0),
('Lee Grant', 'Goalkeeper', 'Manchester United', 0, 0, 0, 0, 0, 0),
('Lee Peltier', 'Defender', 'Cardiff City', 20, 0, 0, 4, 4, 0),
('Leighton Baines', 'Defender', 'Everton', 6, 0, 0, 0, 0, 0),
('Leon Balogun', 'Defender', 'Brighton & Hove Albion', 8, 1, 0, 2, 2, 0),
('Leonardo Bonatini Lohner Maia', 'Forward', 'Wolverhampton Wanderers', 7, 0, 1, 0, 0, 0),
('Leroy Sane', 'Midfielder', 'Manchester City', 31, 10, 10, 1, 1, 0),
('Lewis Cass', 'Defender', 'Newcastle United', 0, 0, 0, 0, 0, 0),
('Lewis Cook', 'Midfielder', 'AFC Bournemouth', 13, 0, 0, 2, 2, 0),
('Lewis Dunk', 'Defender', 'Brighton & Hove Albion', 36, 2, 1, 8, 7, 1),
('Loic Damour', 'Midfielder', 'Cardiff City', 2, 0, 0, 0, 0, 0),
('Loris Karius', 'Goalkeeper', 'Liverpool', 0, 0, 0, 0, 0, 0),
('Luca de la Torre', 'Midfielder', 'Fulham', 0, 0, 0, 0, 0, 0),
('Lucas Digne', 'Defender', 'Everton', 35, 4, 4, 7, 6, 1),
('Lucas Perez', 'Forward', 'West Ham United', 15, 3, 0, 0, 0, 0),
('Lucas Rodrigues Moura da Silva', 'Midfielder', 'Tottenham Hotspur', 32, 10, 0, 3, 3, 0),
('Lucas Torreira', 'Midfielder', 'Arsenal', 34, 2, 2, 9, 8, 1),
('Luciano Vietto', 'Forward', 'Fulham', 20, 1, 4, 1, 1, 0),
('Luka Milivojevic', 'Midfielder', 'Crystal Palace', 38, 12, 2, 10, 10, 0),
('Luke Amos', 'Midfielder', 'Tottenham Hotspur', 1, 0, 0, 0, 0, 0),
('Luke Dreher', 'Midfielder', 'Crystal Palace', 1, 0, 0, 0, 0, 0),
('Luke Shaw', 'Defender', 'Manchester United', 29, 1, 4, 11, 11, 0),
('Lys Mousset', 'Forward', 'AFC Bournemouth', 24, 1, 0, 1, 1, 0),
('Maarten Stekelenburg', 'Goalkeeper', 'Everton', 0, 0, 0, 0, 0, 0),
('Mamadou Sakho', 'Defender', 'Crystal Palace', 27, 0, 0, 2, 2, 0),
('Manolo Gabbiadini', 'Forward', 'Southampton', 12, 1, 0, 0, 0, 0),
('Manuel Lanzini', 'Midfielder', 'West Ham United', 10, 1, 1, 2, 2, 0),
('Marc Albrighton', 'Midfielder', 'Leicester City', 27, 2, 2, 3, 3, 0),
('Marc Guehi', 'Defender', 'Chelsea', 0, 0, 0, 0, 0, 0),
('Marc Navarro Ceciliano', 'Defender', 'Watford', 2, 0, 0, 0, 0, 0),
('Marc Pugh', 'Midfielder', 'AFC Bournemouth', 0, 0, 0, 0, 0, 0),
('Marcos Alonso', 'Defender', 'Chelsea', 31, 2, 4, 6, 6, 0),
('Marcus Bettinelli', 'Goalkeeper', 'Fulham', 7, 0, 0, 1, 1, 0),
('Marcus Rashford', 'Forward', 'Manchester United', 33, 10, 6, 5, 4, 1),
('Mario Lemina', 'Midfielder', 'Southampton', 21, 1, 1, 5, 5, 0),
('Mark Noble', 'Midfielder', 'West Ham United', 31, 5, 5, 8, 7, 1),
('Mark Travers', 'Goalkeeper', 'AFC Bournemouth', 2, 0, 0, 0, 0, 0),
('Marko Arnautovic', 'Forward', 'West Ham United', 28, 10, 4, 3, 3, 0),
('Markus Suttner', 'Defender', 'Brighton & Hove Albion', 0, 0, 0, 0, 0, 0),
('Marouane Fellaini', 'Midfielder', 'Manchester United', 14, 0, 1, 1, 1, 0),
('Martin Dubravka', 'Goalkeeper', 'Newcastle United', 38, 0, 0, 1, 1, 0),
('Martin Kelly', 'Defender', 'Crystal Palace', 13, 0, 0, 2, 2, 0),
('Martin Montoya', 'Defender', 'Brighton & Hove Albion', 25, 0, 1, 4, 4, 0),
('Mason Greenwood', 'Midfielder', 'Manchester United', 3, 0, 0, 0, 0, 0),
('Mason Holgate', 'Defender', 'Everton', 5, 0, 0, 1, 1, 0),
('Matej Vydra', 'Forward', 'Burnley', 13, 1, 1, 1, 1, 0),
('Mateo Kovacic', 'Midfielder', 'Chelsea', 32, 0, 2, 3, 3, 0),
('Mathew Ryan', 'Goalkeeper', 'Brighton & Hove Albion', 34, 0, 0, 2, 2, 0),
('Mathias Jattah-Njie Jorgensen', 'Defender', 'Huddersfield Town', 24, 3, 1, 6, 6, 0),
('Matt Butcher', 'Midfielder', 'AFC Bournemouth', 0, 0, 0, 0, 0, 0),
('Matt Doherty', 'Defender', 'Wolverhampton Wanderers', 38, 4, 5, 5, 5, 0),
('Matt Ritchie', 'Midfielder', 'Newcastle United', 36, 2, 8, 9, 9, 0),
('Matt Targett', 'Defender', 'Southampton', 16, 1, 3, 2, 2, 0),
('Matteo Darmian', 'Defender', 'Manchester United', 6, 0, 0, 0, 0, 0),
('Matteo Guendouzi Olie', 'Midfielder', 'Arsenal', 33, 0, 0, 9, 9, 0),
('Matthew Connolly', 'Defender', 'Cardiff City', 0, 0, 0, 0, 0, 0),
('Matthew Lowton', 'Defender', 'Burnley', 21, 0, 0, 7, 7, 0),
('Matty Daly', 'Midfielder', 'Huddersfield Town', 2, 0, 0, 0, 0, 0),
('Max Harrison Sanders', 'Midfielder', 'Brighton & Hove Albion', 0, 0, 0, 0, 0, 0),
('Max Kilman', 'Defender', 'Wolverhampton Wanderers', 1, 0, 0, 0, 0, 0),
('Max Meyer', 'Midfielder', 'Crystal Palace', 29, 1, 2, 3, 3, 0),
('Maxime Le Marchand', 'Defender', 'Fulham', 26, 0, 1, 5, 5, 0),
('Maya Yoshida', 'Defender', 'Southampton', 17, 0, 1, 0, 0, 0),
('Mesut Ozil', 'Midfielder', 'Arsenal', 24, 5, 2, 2, 2, 0),
('Michael Keane', 'Defender', 'Everton', 33, 1, 2, 2, 2, 0),
('Michael Obafemi', 'Forward', 'Southampton', 6, 1, 1, 1, 1, 0),
('Michail Antonio', 'Midfielder', 'West Ham United', 33, 6, 4, 3, 3, 0),
('Michel Vorm', 'Goalkeeper', 'Tottenham Hotspur', 2, 0, 0, 0, 0, 0),
('Michy Batshuayi', 'Forward', 'Crystal Palace', 11, 5, 0, 0, 0, 0),
('Miguel Angel Almiron Rejala', 'Midfielder', 'Newcastle United', 10, 0, 0, 0, 0, 0),
('Miguel Angel Britos Cabrera', 'Defender', 'Watford', 3, 0, 0, 0, 0, 0),
('Mohamed Diame', 'Midfielder', 'Newcastle United', 29, 0, 0, 3, 3, 0),
('Mohamed Elneny', 'Midfielder', 'Arsenal', 8, 0, 0, 0, 0, 0),
('Mohamed Elyounoussi', 'Midfielder', 'Southampton', 16, 0, 0, 0, 0, 0),
('Mohamed Salah', 'Forward', 'Liverpool', 38, 22, 8, 1, 1, 0),
('Morgan Gibbs-White', 'Midfielder', 'Wolverhampton Wanderers', 26, 0, 1, 1, 1, 0),
('Morgan Schneiderlin', 'Midfielder', 'Everton', 14, 0, 1, 2, 2, 0),
('Moussa Dembele', 'Midfielder', 'Tottenham Hotspur', 10, 0, 0, 1, 1, 0),
('Moussa Sissoko', 'Midfielder', 'Tottenham Hotspur', 29, 0, 3, 2, 2, 0),
('N\'Golo Kante', 'Midfielder', 'Chelsea', 36, 4, 4, 3, 3, 0),
('Naby Deco Keita', 'Midfielder', 'Liverpool', 25, 2, 1, 0, 0, 0),
('Nacho Monreal', 'Defender', 'Arsenal', 22, 1, 3, 5, 5, 0),
('Nampalys Mendy', 'Midfielder', 'Leicester City', 31, 0, 0, 5, 5, 0),
('Nathan Ake', 'Defender', 'AFC Bournemouth', 38, 4, 0, 3, 3, 0),
('Nathan Holland', 'Midfielder', 'West Ham United', 0, 0, 0, 0, 0, 0),
('Nathan Redmond', 'Midfielder', 'Southampton', 38, 6, 4, 3, 3, 0),
('Nathaniel Chalobah', 'Midfielder', 'Watford', 9, 0, 0, 2, 2, 0),
('Nathaniel Clyne', 'Defender', 'AFC Bournemouth', 18, 0, 1, 2, 2, 0),
('Nathaniel Mendez-Laing', 'Midfielder', 'Cardiff City', 20, 4, 1, 0, 0, 0),
('Neeskens Kebano', 'Midfielder', 'Fulham', 7, 0, 0, 0, 0, 0),
('Neil Leonard Dula Etheridge', 'Goalkeeper', 'Cardiff City', 38, 0, 0, 2, 2, 0),
('Nemanja Matic', 'Midfielder', 'Manchester United', 28, 1, 0, 9, 8, 1),
('Nicolas Otamendi', 'Defender', 'Manchester City', 18, 0, 0, 1, 1, 0),
('Nikola Tavares', 'Defender', 'Crystal Palace', 0, 0, 0, 0, 0, 0),
('Nnamdi Ofoborh', 'Midfielder', 'AFC Bournemouth', 0, 0, 0, 0, 0, 0),
('Oleksandr Zinchenko', 'Midfielder', 'Manchester City', 14, 0, 3, 1, 1, 0),
('Oliver Skipp', 'Midfielder', 'Tottenham Hotspur', 8, 0, 0, 0, 0, 0),
('Olivier Giroud', 'Forward', 'Chelsea', 27, 2, 4, 1, 1, 0),
('Onyinye Wilfred Ndidi', 'Midfielder', 'Leicester City', 38, 2, 0, 8, 8, 0),
('Oriol Romeu', 'Midfielder', 'Southampton', 31, 1, 0, 11, 11, 0),
('Oumar Niasse', 'Forward', 'Cardiff City', 18, 0, 0, 0, 0, 0),
('Pablo Zabaleta', 'Defender', 'West Ham United', 26, 0, 1, 4, 4, 0),
('Pape N\'Diaye Souare', 'Defender', 'Crystal Palace', 1, 0, 0, 0, 0, 0),
('Pascal Groß', 'Midfielder', 'Brighton & Hove Albion', 25, 3, 3, 1, 1, 0),
('Patrick van Aanholt', 'Defender', 'Crystal Palace', 36, 3, 2, 3, 3, 0),
('Paul Dummett', 'Defender', 'Newcastle United', 26, 0, 0, 1, 1, 0),
('Paul Pogba', 'Midfielder', 'Manchester United', 35, 13, 9, 6, 6, 0),
('Paulo Dino Gazzaniga', 'Goalkeeper', 'Tottenham Hotspur', 3, 0, 0, 0, 0, 0),
('Pedro Obiang', 'Midfielder', 'West Ham United', 24, 0, 1, 0, 0, 0),
('Pedro Rodriguez', 'Midfielder', 'Chelsea', 31, 8, 2, 2, 2, 0),
('Peter Crouch', 'Forward', 'Burnley', 6, 0, 0, 1, 1, 0),
('Petr Cech', 'Goalkeeper', 'Arsenal', 7, 0, 0, 0, 0, 0),
('Phil Bardsley', 'Defender', 'Burnley', 19, 0, 0, 9, 9, 0),
('Phil Jagielka', 'Defender', 'Everton', 7, 1, 0, 2, 1, 1),
('Phil Jones', 'Defender', 'Manchester United', 18, 0, 1, 1, 1, 0),
('Philip Billing', 'Midfielder', 'Huddersfield Town', 27, 2, 0, 7, 7, 0),
('Philip Foden', 'Midfielder', 'Manchester City', 13, 1, 0, 0, 0, 0),
('Philippe Sandler', 'Defender', 'Manchester City', 0, 0, 0, 0, 0, 0),
('Pierre-Emerick Aubameyang', 'Forward', 'Arsenal', 36, 22, 5, 0, 0, 0),
('Pierre-Emile Højbjerg', 'Midfielder', 'Southampton', 31, 4, 3, 12, 10, 2),
('Rachid Ghezzal', 'Forward', 'Leicester City', 19, 1, 0, 3, 3, 0),
('Rafael Euclides Soares Camacho', 'Midfielder', 'Liverpool', 1, 0, 0, 0, 0, 0),
('Raheem Sterling', 'Forward', 'Manchester City', 34, 17, 10, 3, 3, 0),
('Rajiv van La Parra', 'Midfielder', 'Huddersfield Town', 5, 0, 0, 0, 0, 0),
('Ramadan Sobhi', 'Forward', 'Huddersfield Town', 4, 0, 0, 0, 0, 0),
('Raul Alonso Jimenez Rodriguez', 'Forward', 'Wolverhampton Wanderers', 38, 13, 7, 4, 4, 0),
('Rhys Healey', 'Forward', 'Cardiff City', 3, 0, 0, 0, 0, 0),
('Ricardo Domingos Barbosa Pereira', 'Defender', 'Leicester City', 35, 2, 6, 7, 7, 0),
('Richarlison de Andrade', 'Forward', 'Everton', 35, 13, 1, 7, 6, 1),
('Riyad Mahrez', 'Midfielder', 'Manchester City', 27, 7, 4, 0, 0, 0),
('Rob Holding', 'Defender', 'Arsenal', 10, 0, 0, 1, 1, 0),
('Robbie Brady', 'Midfielder', 'Burnley', 16, 0, 1, 5, 4, 1),
('Robert Kenedy Nunes do Nascimento', 'Midfielder', 'Newcastle United', 25, 1, 1, 1, 1, 0),
('Robert Snodgrass', 'Midfielder', 'West Ham United', 33, 2, 5, 10, 10, 0),
('Roberto Firmino', 'Forward', 'Liverpool', 34, 12, 6, 0, 0, 0),
('Roberto Maximiliano Pereyra', 'Forward', 'Watford', 33, 6, 1, 3, 3, 0),
('Romain Saiss', 'Midfielder', 'Wolverhampton Wanderers', 19, 2, 0, 7, 7, 0),
('Romelu Lukaku', 'Forward', 'Manchester United', 32, 12, 0, 4, 4, 0),
('Rondon', 'Forward', 'Newcastle United', 32, 11, 7, 1, 1, 0),
('Ross Barkley', 'Midfielder', 'Chelsea', 27, 3, 5, 1, 1, 0),
('Ruben Diogo Da Silva Neves', 'Midfielder', 'Wolverhampton Wanderers', 35, 4, 3, 8, 8, 0),
('Ruben Gonçalo Silva Nascimento Vinagre', 'Defender', 'Wolverhampton Wanderers', 17, 0, 0, 1, 1, 0),
('Ruben Loftus-Cheek', 'Midfielder', 'Chelsea', 24, 6, 2, 0, 0, 0),
('Rui Pedro dos Santos Patricio', 'Goalkeeper', 'Wolverhampton Wanderers', 37, 0, 0, 0, 0, 0),
('Ryan Bennett', 'Defender', 'Wolverhampton Wanderers', 34, 1, 0, 12, 12, 0),
('Ryan Bertrand', 'Defender', 'Southampton', 24, 1, 0, 8, 8, 0),
('Ryan Fraser', 'Midfielder', 'AFC Bournemouth', 38, 7, 14, 2, 2, 0),
('Ryan Fredericks', 'Midfielder', 'West Ham United', 15, 1, 0, 5, 5, 0),
('Ryan Giles', 'Midfielder', 'Wolverhampton Wanderers', 0, 0, 0, 0, 0, 0),
('Ryan Guno Babel', 'Forward', 'Fulham', 16, 5, 3, 3, 3, 0),
('Ryan Schofield', 'Goalkeeper', 'Huddersfield Town', 0, 0, 0, 0, 0, 0),
('Ryan Sessegnon', 'Defender', 'Fulham', 35, 2, 6, 0, 0, 0),
('Sadio Mane', 'Forward', 'Liverpool', 36, 22, 1, 2, 2, 0),
('Sam Gallagher', 'Forward', 'Southampton', 4, 0, 0, 0, 0, 0),
('Sam Surridge', 'Forward', 'AFC Bournemouth', 2, 0, 0, 0, 0, 0),
('Sam Vokes', 'Forward', 'Burnley', 20, 3, 0, 0, 0, 0),
('Sam Woods', 'Defender', 'Crystal Palace', 0, 0, 0, 0, 0, 0),
('Samir Nasri', 'Midfielder', 'West Ham United', 5, 0, 2, 0, 0, 0),
('Sandro Ramirez', 'Forward', 'Everton', 0, 0, 0, 0, 0, 0);

DROP TABLE IF EXISTS `teams`;
CREATE TABLE `teams` (
  `Name` varchar(30) NOT NULL,
  `Points` int(11) NOT NULL,
  `Wins` int(11) NOT NULL,
  `Draws` int(11) NOT NULL,
  `Losses` int(11) NOT NULL,
  `GoalsScored` int(11) NOT NULL,
  `GoalsConceded` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `teams` (`Name`, `Points`, `Wins`, `Draws`, `Losses`, `GoalsScored`, `GoalsConceded`) VALUES
('AFC Bournemouth', 45, 13, 6, 19, 56, 70),
('Arsenal', 70, 21, 7, 10, 73, 51),
('Brighton & Hove Albion', 36, 9, 9, 20, 35, 60),
('Burnley', 40, 11, 7, 20, 45, 68),
('Cardiff City', 34, 10, 4, 24, 34, 69),
('Chelsea', 72, 21, 9, 8, 63, 39),
('Crystal Palace', 49, 14, 7, 17, 51, 53),
('Everton', 54, 15, 9, 14, 54, 46),
('Fulham', 26, 7, 5, 26, 34, 81),
('Huddersfield Town', 16, 3, 7, 28, 22, 76),
('Leicester City', 52, 15, 7, 16, 51, 48),
('Liverpool', 97, 30, 7, 1, 89, 22),
('Manchester City', 98, 32, 2, 4, 95, 23),
('Manchester United', 66, 19, 9, 10, 65, 54),
('Newcastle United', 45, 12, 9, 17, 42, 48),
('Southampton', 39, 9, 12, 17, 45, 65),
('Tottenham Hotspur', 71, 23, 2, 13, 67, 39),
('Watford', 50, 14, 8, 16, 52, 59),
('West Ham United', 52, 15, 7, 16, 52, 55),
('Wolverhampton Wanderers', 57, 16, 9, 13, 47, 46);


ALTER TABLE `players`
  ADD PRIMARY KEY (`Name`),
  ADD KEY `Team` (`Team`);

ALTER TABLE `teams`
  ADD PRIMARY KEY (`Name`);


ALTER TABLE `players`
  ADD CONSTRAINT `players_ibfk_1` FOREIGN KEY (`Team`) REFERENCES `teams` (`Name`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
